version: "3.9"
services:
  db:
    image: postgres:latest
    #network_mode: host
    environment:
      POSTGRES_DB: "consumptions"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "6432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  instance1:
    #image: lr5noapiint
    build:
      context: ""
    links:
      - kafka
      - db
    depends_on:
      - kafka
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_CONFIG_NAME=application
      - SPRING_DATASOURCE.DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/consumptions
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_KAFKA_PRODUCER_BOOTSTRAP-SERVERS=kafka:9092
  consumer1:
    #image: lr5noapiint
    build:
      context: ""
    environment:
      - SPRING_CONFIG_NAME=reader1
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=kafka:9092
      #- KAFKA_TOPIC=myTopic
      - SPRING.KAFKA.CONSUMER.GROUP-ID=myGroup
      - SPRING_DATASOURCE.DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/consumptions
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_PROFILES_ACTIVE=consumer
    links:
      - kafka
      - db
    depends_on:
      - kafka
      - db
    ports:
      - 8082:8081